#公共配置
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  #激活哪一个环境的配置文件
  profiles:
    active: dev
  #视图配置
  mvc:
    static-path-pattern: /static/**
  #网络请求配置
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  #连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #Redis
  redis:
    host: 127.0.0.1
    port: 6379
    #password: 1102837040
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xvls.alexander.entity
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号隔离，这样就不用写全路径了，直接写实体名就可以了
  typeAliasesPackage: com.xvls.alexander.entity

  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #    logic-delete-value: 1
    #    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #metaObjectHandler: com.mysiteforme.admin.config.SysMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    #db-config:
    #  id-type: auto  #全局配置主键生成策略，此处是自增长
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

---
#开发环境配置
server:
  #端口
  port: 8082
  servlet:
    context-path: /xvls
spring:
  profiles: dev
  # 数据源配置
  datasource:
    url: jdbc:mysql://139.159.240.77:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&tinyInt1isBit=true&serverTimezone=UTC
    username: myuser
    password: 1102837040